services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mailpit:
        condition: service_started
    env_file:
      - .env.notification-service
    ports:
      - "8081:8080"
    networks:
      - notification-network

  db:
    image: postgres:16
    container_name: notification-postgres
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    volumes:
      - notification_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      - notification-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification-rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - notification-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: notification-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - notification-network

  prometheus:
    image: prom/prometheus:latest
    container_name: notification-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - notification-service
    networks:
      - notification-network
  
  grafana:
    image: grafana/grafana:latest
    container_name: notification-grafana
    ports:
      - "3000:3000"
    env_file:
      - .env.grafana
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - notification-network

volumes:
  notification_pgdata:
  rabbitmq_data:

networks:
  notification-network: